### ISSUE TITLE
Regarding the hugo issue you reported referencing google analytics.

### ISSUE THREAD

**Issue by sharma-rishabh** [nicfab/hugo#1]
I wanted to know what change did you make to fix the problem.

**Comment by nicfab** [comment]
What are you referring to?
Please, clarify it.

**Comment by sharma-rishabh** [comment]
I'm referring to this thread 
https://discourse.gohugo.io/t/error-error-building-site/49340

**Comment by nicfab** [comment]
The solution is here: https://discourse.gohugo.io/t/error-error-building-site/49340/6

**Comment by sharma-rishabh** [comment]
I didn't understand what you meant by that so I thought to raise an issue here for more details. What changes did you make.

**Comment by nicfab** [comment]
It's clear.
I modified the following files:

1.`layout/partials/head.html`
2. `layout/partials/footer/center.html` 

In the first file (`layout/partials/head.html`), I deleted the following block:

```
{{/* To comply with GDPR, cookie consent scripts places in head-end must execute before Google Analytics is enabled */ -}}
{{ if hugo.IsProduction -}}
  {{ $enableGtagForUniversalAnalytics := not .Site.Params.disableGtagForUniversalAnalytics -}}
  {{ if (or $enableGtagForUniversalAnalytics (hasPrefix .Site.GoogleAnalytics "G-")) -}}
    {{ template "_internal/google_analytics_gtag.html" . -}}
  {{ else -}}
    {{ template "_internal/google_analytics_async.html" . -}}
  {{ end -}}
{{ end -}}
```

In the second file (`layout/partials/footer/center.html`) I modified the following row:

**from** `{{ if ne .Site.Params.ui.footer_about_disable nil -}}` **to** `{{ if ne .Site.Params.ui.footer_about_enable nil -}}`.
The change is related to the last string from **disable** to **enable**.

**Comment by sharma-rishabh** [comment]
Thanks a ton.
